import type { Candidate, Requisition } from "@/lib/api";

// Realistic placeholder data used until the FastAPI backend (see /backend) is
// running and seeded. Swapped out transparently once /api/v1/* responds.

export const dummyRequisitions: Requisition[] = [
  {
    id: "req-1",
    position_title: "Warehouse Supervisor",
    department_id: "Warehouse",
    quantity: 2,
    justification: "Backlog in outbound shipments needs a dedicated supervisor.",
    budget_range: "Rp8M–Rp10M",
    status: "Pending Approval",
    created_by: "Rizky",
    created_by_name: "Rizky",
    approved_by_name: null,
    created_at: "2026-09-21T08:00:00Z",
  },
  {
    id: "req-2",
    position_title: "Recruitment Admin",
    department_id: "HRGA",
    quantity: 1,
    justification: "Support growing hiring volume for warehouse roles.",
    budget_range: "Rp6M–Rp8M",
    status: "Approved",
    created_by: "Nabil",
    created_by_name: "Nabil",
    approved_by_name: "Nabil",
    created_at: "2026-09-20T08:00:00Z",
  },
  {
    id: "req-3",
    position_title: "Graphic Designer",
    department_id: "Marketing",
    quantity: 1,
    justification: "Campaign assets backlog for Q4 launch.",
    budget_range: "Rp7M–Rp9M",
    status: "Draft",
    created_by: "Alya",
    created_by_name: "Alya",
    approved_by_name: null,
    created_at: "2026-09-19T08:00:00Z",
  },
  {
    id: "req-4",
    position_title: "Store Crew",
    department_id: "Operations",
    quantity: 8,
    justification: "New store opening next month.",
    budget_range: "Rp4.5M–Rp5.5M",
    status: "Approved",
    created_by: "Dimas",
    created_by_name: "Dimas",
    approved_by_name: "Nabil",
    created_at: "2026-09-18T08:00:00Z",
  },
];

export const dummyCandidates: Candidate[] = [
  {
    id: "cand-aisyah",
    full_name: "Aisyah Putri",
    email: "aisyah@candidate.test",
    applicant_type: "Full-time",
    position_title: "Warehouse Supervisor",
    stage: "Screening",
    folder_path: "Warehouse Supervisor/Screening",
    applied_at: "2026-09-21T00:00:00Z",
    phone: "+62 812-3456-7890",
    cv_file_url: "https://storage.local/cv/Aisyah_Putri_CV.pdf",
    duplicate_type: null,
    folder_id: null,
  },
  {
    id: "cand-rizky",
    full_name: "Rizky Pratama",
    email: "rizky@candidate.test",
    applicant_type: "Daily Worker",
    position_title: "Warehouse Supervisor",
    stage: "Applied",
    folder_path: "Warehouse Supervisor/Applied",
    applied_at: "2026-09-20T00:00:00Z",
    phone: "+62 813-2211-4590",
    cv_file_url: "https://storage.local/cv/Rizky_Pratama_CV.pdf",
    duplicate_type: "same_position",
    folder_id: null,
  },
  {
    id: "cand-dina",
    full_name: "Dina Sari",
    email: "dina@candidate.test",
    applicant_type: "Full-time",
    position_title: "Recruitment Admin",
    stage: "Shortlist",
    folder_path: "Recruitment Admin/Screening",
    applied_at: "2026-09-19T00:00:00Z",
    phone: "+62 811-7788-2200",
    cv_file_url: "https://storage.local/cv/Dina_Sari_CV.pdf",
    duplicate_type: null,
    folder_id: null,
  },
  {
    id: "cand-fajar",
    full_name: "Fajar Adi",
    email: "fajar@candidate.test",
    applicant_type: "Full-time",
    position_title: "Graphic Designer",
    stage: "Applied",
    folder_path: "Graphic Designer/Applied",
    applied_at: "2026-09-18T00:00:00Z",
    phone: "+62 817-4433-9021",
    cv_file_url: "https://storage.local/cv/Fajar_Adi_CV.pdf",
    duplicate_type: "different_position",
    folder_id: null,
  },
  {
    id: "cand-nadia",
    full_name: "Nadia Wulan",
    email: "nadia@candidate.test",
    applicant_type: "Daily Worker",
    position_title: "Recruitment Admin",
    stage: "Hired",
    folder_path: "Recruitment Admin/Hired",
    applied_at: "2026-09-17T00:00:00Z",
    phone: "+62 815-6690-3312",
    cv_file_url: "https://storage.local/cv/Nadia_Wulan_CV.pdf",
    duplicate_type: null,
    folder_id: null,
  },
];

export const recentActivity = [
  { title: "Requisition submitted", detail: "Warehouse Supervisor", time: "2 hours ago", tone: "accent" },
  { title: "Approval recorded", detail: "Recruitment Admin", time: "5 hours ago", tone: "success" },
  { title: "Candidate added", detail: "Aisyah Putri", time: "Yesterday", tone: "info" },
  { title: "Folder created", detail: "Warehouse Supervisor", time: "Yesterday", tone: "primary" },
];

export const candidateIntakeMonths = [
  { label: "Apr", value: 48 },
  { label: "May", value: 60 },
  { label: "Jun", value: 54 },
  { label: "Jul", value: 67 },
  { label: "Aug", value: 72 },
  { label: "Sep", value: 86 },
];

export const sprintModules = [
  { code: "FR-01", label: "Candidate Database", active: true },
  { code: "FR-03", label: "Job Requisition", active: true },
  { code: null, label: "Workforce Planning", active: false },
  { code: null, label: "Candidate Pipeline", active: false },
  { code: null, label: "Interview Scheduling", active: false },
];
